import { SymbolTileData } from "../types/symbol-tile-data";

const DEFAULT_FONT = 'System';
const DEFAULT_FONT_SIZE = 16;

export const DEFALUT_SYMBOL_TILES_COMMON: SymbolTileData[] = [
    {
        textLabelText: 'Yes',
        showTextLabel: true,
        imageLabelSource: require('../assets/yes.svg'),
        showImageLabel: true,
        textLabelFontFamily: DEFAULT_FONT,
        textLabelFontSize:DEFAULT_FONT_SIZE,
        vocalizationText: 'Yes',
        category: 'other',
    },
    {
        textLabelText: 'No',
        showTextLabel: true,
        imageLabelSource: require('../assets/no.svg'),
        showImageLabel: true,
        textLabelFontFamily: DEFAULT_FONT,
        textLabelFontSize: DEFAULT_FONT_SIZE,
        vocalizationText: 'No',
        category: 'other',
    },
    {
        textLabelText: 'Walking',
        showTextLabel: true,
        imageLabelSource: undefined,
        showImageLabel: true,
        textLabelFontFamily: DEFAULT_FONT,
        textLabelFontSize: DEFAULT_FONT_SIZE,
        vocalizationText: 'Walking',
        category: 'verb',  
    },
    {
        textLabelText: 'Running',
        showTextLabel: true,
        imageLabelSource: undefined,
        showImageLabel: true,
        textLabelFontFamily: DEFAULT_FONT,
        textLabelFontSize: DEFAULT_FONT_SIZE,
        vocalizationText: 'Running',
        category: 'verb',
    },
    {
        textLabelText: 'Want',
        showTextLabel: true,
        imageLabelSource: require('../assets/want.jpg'),
        showImageLabel: true,
        textLabelFontFamily: DEFAULT_FONT,
        textLabelFontSize: DEFAULT_FONT_SIZE,
        vocalizationText: 'want',
        category: 'verb',
    },
    {
        textLabelText: 'Mother',
        showTextLabel: true,
        imageLabelSource: undefined,
        showImageLabel: true,
        textLabelFontFamily: DEFAULT_FONT,
        textLabelFontSize: DEFAULT_FONT_SIZE,
        vocalizationText: 'Mother',
        category: 'noun',
    },
    
    {
        textLabelText: 'Father',
        showTextLabel: true,
        imageLabelSource: undefined,
        showImageLabel: true,
        textLabelFontFamily: DEFAULT_FONT,
        textLabelFontSize: DEFAULT_FONT_SIZE,
        vocalizationText: 'Father',
        category: 'noun',
    },
    {
        textLabelText: 'Son',
        showTextLabel: true,
        imageLabelSource: undefined,
        showImageLabel: true,
        textLabelFontFamily: DEFAULT_FONT,
        textLabelFontSize: DEFAULT_FONT_SIZE,
        vocalizationText: 'Son',
        category: 'noun',
    },
    {
        textLabelText: 'Daughter',
        showTextLabel: true,
        imageLabelSource: undefined,
        showImageLabel: true,
        textLabelFontFamily: DEFAULT_FONT,
        textLabelFontSize: DEFAULT_FONT_SIZE,
        vocalizationText: 'Daughter',
        category: 'noun',
    },
    {
        textLabelText: 'I',
        showTextLabel: true,
        imageLabelSource: undefined,
        showImageLabel: true,
        textLabelFontFamily: DEFAULT_FONT,
        textLabelFontSize: DEFAULT_FONT_SIZE,
        vocalizationText: 'I',
        category: 'noun',
    },
    {
        textLabelText: 'Eat',
        showTextLabel: true,
        imageLabelSource: undefined,
        showImageLabel: true,
        textLabelFontFamily: DEFAULT_FONT,
        textLabelFontSize: DEFAULT_FONT_SIZE,
        vocalizationText: 'I am eating',
        category: 'verb',
    },
    {
        textLabelText: 'Computer',
        showTextLabel: true,
        imageLabelSource: undefined,
        showImageLabel: true,
        textLabelFontFamily: DEFAULT_FONT,
        textLabelFontSize: DEFAULT_FONT_SIZE,
        vocalizationText: 'The computer',
        category: 'noun',
    },
    {
        textLabelText: 'Ball',
        showTextLabel: true,
        imageLabelSource: undefined,
        showImageLabel: true,
        textLabelFontFamily: DEFAULT_FONT,
        textLabelFontSize: DEFAULT_FONT_SIZE,
        vocalizationText: 'The ball',
        category: 'noun',
    },
    {
        textLabelText: 'Happy',
        showTextLabel: true,
        imageLabelSource: undefined,
        showImageLabel: true,
        textLabelFontFamily: DEFAULT_FONT,
        textLabelFontSize: DEFAULT_FONT_SIZE,
        vocalizationText: 'happy',
        category: 'adjective',
    },
    {
        textLabelText: 'Sad',
        showTextLabel: true,
        imageLabelSource: undefined,
        showImageLabel: true,
        textLabelFontFamily: DEFAULT_FONT,
        textLabelFontSize: DEFAULT_FONT_SIZE,
        vocalizationText: 'sad',
        category: 'adjective',
    },

]

export const DEFAULT_SYMBOL_FEELINGS: SymbolTileData[] =
[
    {
        textLabelText: 'Happy',
        showTextLabel: true,
        imageLabelSource: undefined,
        showImageLabel: true,
        textLabelFontFamily: DEFAULT_FONT,
        textLabelFontSize: DEFAULT_FONT_SIZE,
        vocalizationText: 'Happy',
        category: 'adjective',
    },
    {
        textLabelText: 'Sad',
        showTextLabel: true,
        imageLabelSource: undefined,
        showImageLabel: true,
        textLabelFontFamily: DEFAULT_FONT,
        textLabelFontSize: DEFAULT_FONT_SIZE,
        vocalizationText: 'sad',
        category: 'adjective',
    },
    {
        textLabelText: 'Frustrated',
        showTextLabel: true,
        imageLabelSource: undefined,
        showImageLabel: true,
        textLabelFontFamily: DEFAULT_FONT,
        textLabelFontSize: DEFAULT_FONT_SIZE,
        vocalizationText: 'Frustrated',
        category: 'adjective',
    },
    {
        textLabelText: 'Anxious',
        showTextLabel: true,
        imageLabelSource: undefined,
        showImageLabel: true,
        textLabelFontFamily: DEFAULT_FONT,
        textLabelFontSize: DEFAULT_FONT_SIZE,
        vocalizationText: 'anxious',
        category: 'adjective',
    },
    {
        textLabelText: 'Calm',
        showTextLabel: true,
        imageLabelSource: undefined,
        showImageLabel: true,
        textLabelFontFamily: DEFAULT_FONT,
        textLabelFontSize: DEFAULT_FONT_SIZE,
        vocalizationText: 'Calm',
        category: 'adjective',
    },
    {
        textLabelText: 'Angry',
        showTextLabel: true,
        imageLabelSource: undefined,
        showImageLabel: true,
        textLabelFontFamily: DEFAULT_FONT,
        textLabelFontSize: DEFAULT_FONT_SIZE,
        vocalizationText: 'angry',
        category: 'adjective',
    },
    {
        textLabelText: 'Confused',
        showTextLabel: true,
        imageLabelSource: undefined,
        showImageLabel: true,
        textLabelFontFamily: DEFAULT_FONT,
        textLabelFontSize: DEFAULT_FONT_SIZE,
        vocalizationText: 'Confused',
        category: 'adjective',
    },
    {
        textLabelText: 'Tired',
        showTextLabel: true,
        imageLabelSource: undefined,
        showImageLabel: true,
        textLabelFontFamily: DEFAULT_FONT,
        textLabelFontSize: DEFAULT_FONT_SIZE,
        vocalizationText: 'Tired',
        category: 'adjective',
    },
]

export const DEFALUT_SYMBOL_THERAPY: SymbolTileData[] = [
    {
        textLabelText: 'Happy',
        showTextLabel: true,
        imageLabelSource: undefined,
        showImageLabel: true,
        textLabelFontFamily: DEFAULT_FONT,
        textLabelFontSize: DEFAULT_FONT_SIZE,
        vocalizationText: 'Happy',
        category: 'adjective',
    },
]

export const DEFALUT_SYMBOL_NEEDS: SymbolTileData[] =[
    {
        textLabelText: 'Help',
        showTextLabel: true,
        imageLabelSource: undefined,
        showImageLabel: true,
        textLabelFontFamily: DEFAULT_FONT,
        textLabelFontSize: DEFAULT_FONT_SIZE,
        vocalizationText: 'Help',
        category: 'verb',
    },
    {
        textLabelText: 'Break',
        showTextLabel: true,
        imageLabelSource: undefined,
        showImageLabel: true,
        textLabelFontFamily: DEFAULT_FONT,
        textLabelFontSize: DEFAULT_FONT_SIZE,
        vocalizationText: 'Break',
        category: 'adjective',
    },
    {
        textLabelText: 'Water',
        showTextLabel: true,
        imageLabelSource: undefined,
        showImageLabel: true,
        textLabelFontFamily: DEFAULT_FONT,
        textLabelFontSize: DEFAULT_FONT_SIZE,
        vocalizationText: 'Water',
        category: 'noun',
    },
    {
        textLabelText: 'Quiet',
        showTextLabel: true,
        imageLabelSource: undefined,
        showImageLabel: true,
        textLabelFontFamily: DEFAULT_FONT,
        textLabelFontSize: DEFAULT_FONT_SIZE,
        vocalizationText: 'Quiet',
        category: 'adjective',
    },
    {
        textLabelText: 'Support',
        showTextLabel: true,
        imageLabelSource: undefined,
        showImageLabel: true,
        textLabelFontFamily: DEFAULT_FONT,
        textLabelFontSize: DEFAULT_FONT_SIZE,
        vocalizationText: 'Support',
        category: 'verb',
    },
    {
        textLabelText: 'Time',
        showTextLabel: true,
        imageLabelSource: undefined,
        showImageLabel: true,
        textLabelFontFamily: DEFAULT_FONT,
        textLabelFontSize: DEFAULT_FONT_SIZE,
        vocalizationText: 'Time',
        category: 'other',
    },
]

export const DEFALUT_SYMBOL_COMPUTER_TAB: SymbolTileData[] = [
    {
        textLabelText: 'Ipad',
        showTextLabel: true,
        imageLabelSource: undefined,
        showImageLabel: true,
        textLabelFontFamily: DEFAULT_FONT,
        textLabelFontSize: DEFAULT_FONT_SIZE,
        vocalizationText: 'Ipad',
        category: 'noun',
    },
]