export const AVAILABLE_CATEGORY_COLORS = [
  "#F39D2A",
  "#23B883",
  "#4085F3",
  "#CEC4F7",
  "#ED4649",
  "#F7732A",
  "#AEDEED",
  "#86CA2E",
  "#A75CF4",
  "#EA4C99",
  "#ffffff",
  "#000000",
];

export const DEFAULT_OTHER_CATEGORY_COLOR = AVAILABLE_CATEGORY_COLORS[0];
export const DEFAULT_NOUN_CATEGORY_COLOR = AVAILABLE_CATEGORY_COLORS[1];
export const DEFAULT_ADJECTIVE_CATEGORY_COLOR = AVAILABLE_CATEGORY_COLORS[2];
export const DEFAULT_VERB_CATEGORY_COLOR = AVAILABLE_CATEGORY_COLORS[3];
